### ISSUE TITLE
Potential troll/shill vector in chat

### ISSUE THREAD

**Issue by LiteBit** [shadowproject/shadow#56]
Currently we have the ability to select different addresses to post comments in both Private and Group chat. This could be used to troll/shill with sock accounts and nobody would be the wiser.

![capture](https://cloud.githubusercontent.com/assets/6236019/18874589/5d4a4278-8490-11e6-9f98-6dc5e8f9d0e5.JPG)

Sample image is an example of this. All those posts were made from my account but either aren't identified, linked or invited by my account or other people in the chat.

A solution would be to eliminate the drop down address selector and only allow address invited to chat session or address who created chat session.

**Comment by LiteBit** [comment]
This is probably more likely in group chat over private chat

**Comment by kewde** [comment]
Yes,

The next update should take care of this a bit, not perfectly but to some degree.
We'll be locking the dropdown if you've ever sent a message. A user would have to constantly delete his messages and pick another address.

Trolls and shills will always be a problem, regardless of the solution you throw at it.

Currently we can not enforce restricting it to invited-only addresses due to the cryptography and time-limit of messages that drives our engine.
